title: Relaycorp Documentation

markdown: kramdown

destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.2.7-r
color_scheme: dark

footer_content: "Copyright &copy; 2020 Relaycorp, Inc."

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
